# Generated by Django 3.0.9 on 2020-08-10 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ShopDept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sort_order', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StorageLoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sort_order', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('method', models.TextField()),
                ('items', models.ManyToManyField(to='shoplist_app.Item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='shop_dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoplist_app.ShopDept'),
        ),
        migrations.AddField(
            model_name='item',
            name='storage_loc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoplist_app.StorageLoc'),
        ),
    ]
