# Generated by Django 3.0.9 on 2020-08-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplist_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='favourite',
            field=models.BooleanField(default=True),
        ),
    ]
