# Generated by Django 3.0.9 on 2020-08-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplist_app', '0002_item_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='cook_time',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='ingredients',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='serves',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='short_name',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='total_time',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
