# Generated by Django 3.0.9 on 2020-09-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplist_app', '0003_auto_20200817_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='cook_time',
            field=models.SmallIntegerField(verbose_name='Cooking Time (mins)'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='method',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='total_time',
            field=models.SmallIntegerField(verbose_name='Total Time (mins)'),
        ),
    ]
